// import React from "react";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes";

// import "../globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Auth",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <ClerkProvider
//     appearance={{
//       baseTheme: dark,
//     }}>
//     <html lang="en">
//         <body className={`${ inter.className } bg-dark-1`}>
//             <div className="w-full flex justify-center items-center min-h-screen">
//                 { children }
//             </div>
//         </body>
//     </html>
//     </ClerkProvider>
//   );
// }

import React from "react";
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

// Ensure these styles are loaded, they can be in globals.css or a specific stylesheet
import "../globals.css";

const ParticleRing = dynamic(() => import("./ParticleRing"), { ssr: false }); // Force ParticleRing to be client-side only

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={`${inter.className} bg-dark-1`}>
          <div className="relative w-full h-full min-h-screen">
            {/* Particle Ring as Background */}
            <div className="fullscreen-bg">
              <ParticleRing />
            </div> 
            {/* Content Wrapper - ensures login card is centered and over the background */}
            <div className="content-wrapper">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}